/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * laporantransaksi.java
 *
 * Created on May 21, 2017, 4:54:37 PM
 */
package tiketkonser;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nadia
 */
public class laporantransaksi extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn; 
        String host="localhost";
        String db="tiketkonser";
        String user="root";
        String pass=""; 
    
    int beli,bayar,total,kembalian,harga;

    /** Creates new form laporantransaksi */
    public laporantransaksi() {
        initComponents();
        setJTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TLaporan = new javax.swing.JTable();
        BCetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TLaporan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 730, 550));

        BCetak.setText("Cetak Laporan");
        BCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCetakActionPerformed(evt);
            }
        });
        getContentPane().add(BCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 290, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg-laporan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(TxtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1030, 0, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCetakActionPerformed
// TODO add your handling code here:
    cetak();
}//GEN-LAST:event_BCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporantransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporantransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporantransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporantransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new laporantransaksi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCetak;
    private javax.swing.JTable TLaporan;
    private javax.swing.JTextField TxtNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getData(){
  
  try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
        String sql="Select * from transaksi";
        PreparedStatement st=(PreparedStatement) conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;

       // Menampilkan ke JTable  melalui tabModel
        String Tanggal,No,Nama,Kelas,Jenis,Harga,Bayar,Kembalian;
        int no=0;
        while(rs.next()){
         no=no+1;
         Tanggal=rs.getString("tanggal_transaksi");
         No=rs.getString("no_tiket");
         Nama=rs.getString("nama");
         Kelas=rs.getString("kelas");
         Jenis=rs.getString("jenis_tiket");
         Harga=rs.getString("harga");
         Bayar=rs.getString("bayar");
         Kembalian=rs.getString("kembalian");

         Object Data[]={Tanggal,No,Nama,Kelas,Jenis,Harga,Bayar,Kembalian};
         tabModel.addRow(Data);
        }
          // Tutup Koneksi
          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {         // Ketika Gagal Memanggil Driver
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {                   // Ketika Gagal Sql   // import java.sql.SQLException
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }    // Akhir Method getData
    
    private void setJTable(){
    String [] JudulKolom={"tanggal_transaksi","no_tiket","nama","kelas","jenis_tiket","harga","bayar","kembalian"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false, false};
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TLaporan.setModel(tabModel);
    TLaporan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TLaporan.getColumnModel().getColumn(0).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(1).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(2).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(3).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(4).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(5).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(6).setPreferredWidth(100);
    TLaporan.getColumnModel().getColumn(7).setPreferredWidth(100);

    getData();

}// Akhir Method setJTable
    
    class JTextFieldFilter extends PlainDocument {

    public static final String numeric = "0123456789";
    public static final String huruf = " abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXXYZ";
    public static final String alamat = " 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXXYZ.-()";
    protected String acceptedChars = null;
    protected boolean negativeAccepted = false;

    public JTextFieldFilter(String acceptedchars) {
    acceptedChars = acceptedchars;
    }

    public void setNegativeAccepted(boolean negativeaccepted) {
    if (acceptedChars.equals(numeric) || (acceptedChars.equals(huruf))){
    negativeAccepted = negativeaccepted;
    acceptedChars += "-";
    }

    }

    @Override
    public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
    if (str == null)
    return;

    for (int i = 0; i < str.length(); i++) {
    if (acceptedChars.indexOf(str.valueOf(str.charAt(i))) == -1)
    return;
    }

    if (negativeAccepted && str.indexOf("-") != -1) {
    if (str.indexOf("-") != 0 || offset != 0) {
    return;
    }
    }

    super.insertString(offset, str, attr);
    }
    }
    
    void cetak(){
    JasperReport jasRep;
    JasperPrint jasPri;
    Map<String, Object> Nama = new HashMap<String, Object>();
    JasperDesign jasDes;
    
    try {
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
        
        File report = new  File("src/laporan/laporantransaksi.jrxml");
        jasDes = JRXmlLoader.load(report);
        HashMap hashMap = new HashMap();
        hashMap.put("no_tiket", TxtNo.getText());
        jasRep = JasperCompileManager.compileReport(jasDes);
        jasPri = JasperFillManager.fillReport(jasRep, hashMap, conn);
        JasperViewer.viewReport(jasPri, false);
            //JasperPrintManager,printReport(jasPri, true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
}
