/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on May 20, 2017, 7:15:39 AM
 */
package tiketkonser;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Nadia
 */
public class login extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    String host="localhost";
    String db="tiketkonser";  // perpus_NimAnda
    String user="root";
    String pass="";
    Connection conn;

    /** Creates new form login */
    public login() {
        initComponents();
        
        txtuser.setDocument(new JTextFieldFilter(JTextFieldFilter.huruf));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        bMasuk = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel2.setText("Kata Sandi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        txtuser.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 280, -1));

        txtpass.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 280, -1));

        bMasuk.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        bMasuk.setText("Masuk");
        bMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMasukActionPerformed(evt);
            }
        });
        getContentPane().add(bMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        bBatal.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });
        getContentPane().add(bBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        jLabel4.setText("Masuk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel5.setText("Nama Pengguna");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-bg-pix-pisan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void bMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMasukActionPerformed
// TODO add your handling code here:
        String sql;
        String username=txtuser.getText();
        String password=txtpass.getText();
        try {      
        Class.forName("com.mysql.jdbc.Driver");
        conn  =DriverManager.getConnection("jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pass);
        sql ="Select * from user WHERE username ='" +txtuser.getText() + "'";
        PreparedStatement st = conn.prepareStatement(sql);
        ResultSet rs =st.executeQuery();      
        if (rs.next()) {
             String pass = rs.getString("Password");
             String bagian = rs.getString("Bagian");
             if (password.equals(pass)){
                 JOptionPane.showMessageDialog(this, "Login Berhasil");
                 if(bagian.equals("Admin")){
                   menuadmin tampil = new menuadmin();
                   tampil.setVisible(true);
                 }
                 else
                 {
                   menusirkulasi tampil = new menusirkulasi();
                   tampil.setVisible(true);
                 }
             }
             else
                  JOptionPane.showMessageDialog(this, "Ada Kesalahan pada Username/Password");
        } else
          JOptionPane.showMessageDialog(this, "Ada Kesalahan pada Username/Password");
      }
      catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
      }
}//GEN-LAST:event_bMasukActionPerformed

private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
// TODO add your handling code here:
    txtuser.setText("");
    txtpass.setText("");
}//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

    class JTextFieldFilter extends PlainDocument {

    public static final String numeric = "0123456789";
    public static final String huruf = " abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXXYZ";
    public static final String alamat = " 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXXYZ.-()";
    protected String acceptedChars = null;
    protected boolean negativeAccepted = false;

    public JTextFieldFilter(String acceptedchars) {
    acceptedChars = acceptedchars;
    }

    public void setNegativeAccepted(boolean negativeaccepted) {
    if (acceptedChars.equals(numeric) || (acceptedChars.equals(huruf))){
    negativeAccepted = negativeaccepted;
    acceptedChars += "-";
    }

    }

    @Override
    public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
    if (str == null)
    return;

    for (int i = 0; i < str.length(); i++) {
    if (acceptedChars.indexOf(str.valueOf(str.charAt(i))) == -1)
    return;
    }

    if (negativeAccepted && str.indexOf("-") != -1) {
    if (str.indexOf("-") != 0 || offset != 0) {
    return;
    }
    }

    super.insertString(offset, str, attr);
    }
    }
}
